### ISSUE TITLE
Troubleshooting

### ISSUE THREAD

**Issue by tallmtt** [prokosna/sola_mpd#77]
Where is the proper place to ask for help?

I have mpd installed and can stream over http controlled with mpc. I am running solaMPD via docker on the same headless server as mpd is installed on. 

For some reason it cannot connect to the mpd server. I have tried localhost, my actual domain name, and external IP address.

Do I need to also open port 6600 on the docker image to connect to mpd running on the server?

**Comment by prokosna** [comment]
Hi @tallmtt, thanks for fileing the issue. This is the right place for any questions.

Would you try the following steps?
```
$ cd path/to/sola_mpd
$ git fetch origin docker-host-access
$ git checkout docker-host-access
$ docker/remove.sh
$ docker/start.sh
```
And please use `host.docker.internal` as a HOST parameter rather than `localhost` when connecting to the mpd.

If it works, I will merge this to the `main` branch with documentation.

If you still have the issue, please also share the Chrome console log message when you try to connect the mpd on Sola MPD.

--
>  I have tried localhost, my actual domain name, and external IP address.
* actual domain name
* external IP address

are supposed to work. But I need more information about your network setup for investigation.

* localhost

won't work because `localhost` in the container means the container itself rather than your host machine where mpd is running.

> Do I need to also open port 6600 on the docker image to connect to mpd running on the server?

You don't need this.

**Comment by prokosna** [comment]
I merged the update. Please re-open the issue if you still have the problem when you use `host.docker.internal`.
